{
 "title": "Nginx VTS",
 "description": "Show stats from https://github.com/vozlt/nginx-module-vts without exporter.",
 "tags": [
  "prometheus",
  "nginx",
  "nginx-module-vts"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nginx_vts_server_bytes_total, instance)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(nginx_vts_server_bytes_total{instance=~\"$Instance\"}, host)"
    }
   },
   {
    "name": "Upstream",
    "query": {
     "query": "label_values(nginx_vts_upstream_bytes_total{instance=~\"$Instance\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Writing",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"writing\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"reading\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"waiting\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_requests_total{instance=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  { "title": "by server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Server Requests delta/sec (uptstream)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"$Upstream\", code!=\"total\"} [1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Server Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_cache_total{instance=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "by upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\",code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}) by (upstream)",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}